### ISSUE TITLE
Not all errors added when using same code on multiple fields

### ISSUE THREAD

**Issue by wimdeblauwe** [alimate/errors-spring-boot-starter#102]
Suppose this class:

```
public class UserCreationParameters {


    @Email(message = PROPERTY_IS_NOT_EMAIL)
    @NotEmpty(message = PROPERTY_SHOULD_NOT_BE_EMPTY)
    private String email;

    @NotEmpty(message = PROPERTY_SHOULD_NOT_BE_EMPTY)
    private String firstName;

    @NotEmpty(message = PROPERTY_SHOULD_NOT_BE_EMPTY)
    private String lastName;

    @NotEmpty(message = PROPERTY_SHOULD_NOT_BE_EMPTY)
    private String password;

   ... 
}
```

With the constants:

```
public final class ErrorCodes {
    public static final String PROPERTY_SHOULD_NOT_BE_EMPTY = "PROPERTY_SHOULD_NOT_BE_EMPTY";
    public static final String PROPERTY_IS_NOT_EMAIL = "PROPERTY_IS_NOT_EMAIL";
}
```

If I test this with the 4 fields of `UserCreationParameters` empty, I only get 1 item in the errors array:

I checked in `SpringValidationWebErrorHandler` and there are 4 errors in the `BindingResult`. However, since they map to the same key and they are put in a `Set` only 1 remains.

It is possible to support re-use of error codes to avoid having a lot of nearly the same translations of the error codes to error messages? I wrote a custom `HttpErrorAttributesAdapter` to add the name of the property in the resulting JSON so I can have the same error codes.

**Comment by alimate** [comment]
@wimdeblauwe That's right. We've designed this small library to have _one error code for each error case_. That's why we maintain the error codes inside an instance of a `Set`.
Anyway, we could evaluate the possibility of this feature to `1.5` release. For example, we can report one error code along with more than one argument describing the related fields.

**Comment by wimdeblauwe** [comment]
Ok, great that you are open to this. Ideally, if there is only a single error message for a single annotation, it would be great if we could just define this in a central way, so that I can skip repeating the `message = PROPERTY_SHOULD_NOT_BE_EMPTY` argument for each `@NotEmpty` annotation. (Adding it to have a specific error message as an override should remain possible of course).

**Comment by wimdeblauwe** [comment]
Issue can be closed as I wrote my own library -> https://github.com/wimdeblauwe/error-handling-spring-boot-starter

**Comment by Tazaf** [comment]
Would it be possible to reopen this issue?

I came accross it recently and, even though I technically can declare a message by error case, it would make much more sense to support multiple error messages for one error type.

This is a little frustrating to see that #105 seems to tick all the boxes but hasn't been merged yet 😞
