### ISSUE TITLE
How to make use of fingerprint id to correlate with log exception detail?

### ISSUE THREAD

**Issue by seedarren** [alimate/errors-spring-boot-starter#106]
1. How to make use of fingerprint id to correlate with log exception detail? 
2. Do you plan to support current timestamp in error message?

**Comment by alimate** [comment]
You can register a [`WebErrorHandlerPostProcessor`](https://github.com/alimate/errors-spring-boot-starter/blob/master/src/main/java/me/alidg/errors/WebErrorHandlerPostProcessor.java). Then it's possible to:
 - Save the fingerprint to some persistent storage or even log it for further investigation
 - Add timestamp

**Comment by seedarren** [comment]
thanks
