### ISSUE TITLE
Add support for required headers

### ISSUE THREAD

**Issue by bfkelsey** [alimate/errors-spring-boot-starter#20]
Currently a 500 will be returned if a header that is required is missing. Standard Spring will return a 400 which should be the default behavior of this tool.

I did a little searching and it seems Spring just uses a `ServletRequestBindingException` for missing headers. This doesn't provide any way to get the header name or type so it would be a little hard to change the message. The default message is something like: "Missing request header 'name' for method parameter of type String"

**Comment by bfkelsey** [comment]
This seems to have been fixed in Spring 5.1 https://jira.spring.io/browse/SPR-14818. So will be available in the upcoming spring boot 2.1 release.

**Comment by alimate** [comment]
Closing in favor of #29. Thank you for raising this issue 👍👍
