### ISSUE TITLE
Allow overriding included implementations

### ISSUE THREAD

**Issue by bfkelsey** [alimate/errors-spring-boot-starter#22]
It should be possible to override the built in error handlers with a custom solution if needed. Because of not being able to do this using this library as is won't work because of #20. 

Otherwise, the built-in handlers should be more specific on which exceptions they can handle.

**Comment by alimate** [comment]
I agree. I guess the issue would be resolved if the `canHandle` method on each built-in error handler be more specific about what it can handle, as you suggested.
