### ISSUE TITLE
Bean Validation: does the message parameters get supported?

### ISSUE THREAD

**Issue by php-coder** [alimate/errors-spring-boot-starter#73]
Does the messages parameters (`Message parameters are string literals enclosed in {}`, see https://docs.jboss.org/hibernate/validator/6.1/reference/en-US/html_single/#section-message-interpolation) is supported?

For example, would the following work?
```java
@NotBlank(message = "{username.required}")
private final String username;
```

**Comment by alimate** [comment]
Yes, we support that. As a matter of fact, if you pass an invalid value as the `username` parameter, the   starter extracts the actual message based on the `username.required` property in a `properties` file.

Please take a look at:
 - https://github.com/alimate/errors-spring-boot-starter#error-codes
 - https://github.com/alimate/errors-spring-boot-starter#error-message
 - https://github.com/alimate/errors-spring-boot-starter#exposing-named-arguments
 - https://github.com/alimate/errors-spring-boot-starter/blob/master/EXPOSED-ARGS.md#validation-exceptions

Ping me if you have more questions.

**Comment by php-coder** [comment]
Thanks!

It wasn't clear whether it supported or not from examples. I briefly look at the code and didn't find a test for that.
