### ISSUE TITLE
Add support to pick fields of the Exception class

### ISSUE THREAD

**Issue by rezaep** [alimate/errors-spring-boot-starter#78]
Usually, we put valuable data inside the exceptions like traceId, the requested URI, the rejected or failed input values and...
That will be awesome if you add an option to pick the fields of the Exception class and add them to the error representation JSON. For now, It just ignores all fields of the Exception class.

The Exception class:

```
@ExceptionMapping(statusCode = HttpStatus.NOT_FOUND, errorCode = "the_error_code")
@NoArgsConstructor
@AllArgsConstructor
public class NotFoundException extends Exception {
    private String traceId;
}
```

What I expect:

```
{
  "errors": [
    {
      "code": "the_error_code",
      "message": "the_error_message",
      "traceId": "some data here or null if not set"
    }
  ]
}
```

What I get:

```
{
  "errors": [
    {
      "code": "the_error_code",
      "message": "the_error_message"
    }
  ]
}
```

**Comment by zarebski-m** [comment]
It is already possible to expose error arguments: https://github.com/alimate/errors-spring-boot-starter#exposing-named-arguments

With combination with https://github.com/alimate/errors-spring-boot-starter#customizing-the-error-representation you can customize your error reprezentation even further.

**Comment by rezaep** [comment]
Thanks for the fast response @zarebski-m. Good to see that you handle this case.
I have another question. Is it possible to push some common fields to a parent exception and still use @ExposeAsArg annotation?

Example:

```
public class BaseException extends Exception {
    @ExposeAsArg(0)
    private String traceId;
}
```

```
@ExceptionMapping(statusCode = HttpStatus.NOT_FOUND, errorCode = "the_error_code")
public class MediaNotFoundException extends BaseException {

}
```

And expect to get this JSON result?

JSON result:JSON result:
```
{
  "errors": [
    {
      "code": "the_error_code",
      "message": "the_error_message"
      "arguments": {
        "traceId": "trace ID"
      }
    }
  ]
}
```

**Comment by alimate** [comment]
@rezaep This would work if you add a getter method for the `traceId` field:
```java
public static class BaseException extends Exception {
        private String traceId;

        @ExposeAsArg(value = 0, name = "traceId")
        public String getTraceId() {
            return traceId;
        }
    }
```
